version: '3'
services:
  web:
    image: nginx:${NGINX_VERSION}
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - ${WEB_PORT}:80
    networks:
      - lbpapp

  engine:
    build: ./docker/php
    volumes:
      - ./:/var/www/html
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
        MYSQL_DATABASE: ${MYSQL_DATABASE} 
        MYSQL_HOST: ${MYSQL_HOST} 
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - lbpapp
  
  adminer:
    image: adminer
    ports:
      - ${WEB_ADMINER_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DEFAULT_DB_HOST: mysql
    depends_on: 
      - mysql
    networks:
      - lbpapp

  mysql:
    image: mysql:8
    container_name: ermak-db
    ports:
        - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
      - ./dbcreation.sql:/tmp/dbcreation.sql
      - ./import.sh:/tmp/import.sh
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
        MYSQL_DATABASE: ${MYSQL_DATABASE} 
        MYSQL_HOST: ${MYSQL_HOST} 
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
        - lbpapp

networks:
  lbpapp:
    driver: "bridge"